### ISSUE TITLE
Update to zookeeper 3.4.10

### ISSUE THREAD

**Issue by oppegard** [cppforlife/zookeeper-release#4]
Hi Dmitriy,

We use your zookeeper release for coordination of our SolrCloud deployment. The latest SolrCloud (6.6) has bumped their zookeeper dependency from 3.4.6 to 3.4.10. Is it possible to upgrade your release to zookeeper 3.4.10?

Thanks,
Glenn from Tracker team

**Comment by cppforlife** [comment]
@oppegard 0.0.6 is out.

**Comment by oppegard** [comment]
Thanks!
