### ISSUE TITLE
Creating manifest issue

### ISSUE THREAD

**Issue by ramyasg** [cppforlife/zookeeper-release#5]
We are attempting to upload a stemcell downloaded from bosh stemcells section onto our director. While doing that, we are following the steps mentioned in bosh and referring to the zookeeper example of the manifest file. Reference link - https://docs.cloudfoundry.org/deploying/common/deploy.html and http://bosh.cloudfoundry.org/docs/uploading-stemcells.html
We are clueless as to how do we make the director aware of the manifest file. Is there any steps to do this as both the links above talk about creating manifest file but actual commands are missing. 
After creating the manifest file, when we try to upload stemcell which was downloaded from bosh, it fails. 
We get the following error - 
```
Task 90 | 10:57:08 | Update stemcell: Extracting stemcell archive (00:00:04)
Task 90 | 10:57:13 | Update stemcell: Verifying stemcell manifest (00:00:00)
Task 90 | 10:57:28 | Update stemcell: Checking if this stemcell already exists (00:00:00)
Task 90 | 10:57:28 | Update stemcell: Uploading stemcell bosh-vsphere-esxi-ubuntu-trusty-go_agent/3468 to the cloud (00:00:28)
                   L Error: Unknown CPI error 'Unknown' with message 'getaddrinfo: Name or service not known (esx-mcp02.gtci-dev.com:443)' in 'create_stemcell' CPI method
Task 90 | 10:57:56 | Error: Unknown CPI error 'Unknown' with message 'getaddrinfo: Name or service not known (esx-mcp02.gtci-dev.com:443)' in 'create_stemcell' CPI method

Task 90 Started  Fri Oct 13 10:57:08 UTC 2017
Task 90 Finished Fri Oct 13 10:57:56 UTC 2017
Task 90 Duration 00:00:48
Task 90 error

Uploading stemcell file:
  Expected task '90' to succeed but state is 'error'
```
Any pointers in this would help us out in moving forward.

**Comment by cppforlife** [comment]
> getaddrinfo: Name or service not known (esx-mcp02.gtci-dev.com:443)

this error indicates that your dns resolution does not work. CPI cannot resolve above domain so that it can upload stemcell.

since this error is not related to this release. ill close this one, but feel free to reach out in https://github.com/cloudfoundry/bosh
