### ISSUE TITLE
New version of bosh-cli give warning during run-errand

### ISSUE THREAD

**Issue by degaurab** [cppforlife/zookeeper-release#8]
Hi @cppforlife,
Can we update the smoke-test `instances name` in manifest. Newer version of bosh-cli gives following warning:
```
 Warning: Ambiguous request: the requested errand name 'smoke-tests' matches both a job name and an errand instance group name. Executing errand on all relevant instances with job 'smoke-tests'.
```

**Comment by cppforlife** [comment]
@degaurab well smoke-tests instance group is a pretty nice name. im thinking of waiting out until we stop using instance group names as errand names.
